### ISSUE TITLE
Hu moments v1 - Roadmap

### ISSUE THREAD

**Issue by naikymen** [darksideoftheshmoo/rcell2#25]
- [ ] Extraer mascaras
- [ ] Correr Hu moments
- [ ] Clasificar con kmeans

**Comment by naikymen** [comment]
Las funciones para extraer las mascaras del TSV output de CellID mask_mod ya funcionan bien.

Queda pendiente:

- [ ] Chequear que las funciones para sacar esa info de los TIFF siguen andando con .out de la opcion `-m`.
- [ ] Armar funciones para importar datos de las nuevas opciones en mask_mod que implementó @gaspanico

**Comment by gaspanico** [comment]
Probar diferentes variantes de clasificación para ver qué da mejor:

- [ ] Con vs. sin normalización de los diferentes Hu moments

- [ ] Con vs. sin interior pixels

- [ ] Investigar cómo otros grupos lo han hecho. Por ejemplo [este paper](https://arxiv.org/ftp/arxiv/papers/2007/2007.09859.pdf).
